### PR TITLE
Chore: Enable followees and dissolve delay in SNS neurons

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Enable followee management and increasing dissolve delay.

# Changes

* Add comment in `pathForRouteId`
* Remove ENABLE_SNS_2 from SnsNeuronFollowingCard and IncreaseSnsDissolveDelayButton

### CODE REVIEW

**Comment by peterpeterparker** [comment]
I provided and described the route id fix earlier -> https://github.com/dfinity/nns-dapp/pull/1615

**Comment by lmuntaner** [comment]
> I provided and described the route id fix earlier -> #1615

Thanks! I'll wait for your PR then

**Comment by lmuntaner** [comment]
@peterpeterparker I updated the PR. I kept the comment in the util but removed the change

**Review by peterpeterparker — APPROVED** [review]
Thx

**Pull request merged**
