### PR TITLE
Update snsdemo commit

### PR DESCRIPTION
**Pull request by sa-github-api**
# Motivation
We would like to keep the testing environment, provided by snsdemo, up to date.

# Changes

## Automatic changes

* Updated `snsdemo` version in `dfx.json`.
* Ensured that the `dfx` version and IC commit in `dfx.json` match `snsdemo`.
* Updated the NNS canister `.did` file imports and derived rust code.
* Changes in the Rust types.

## Manual changes

* `.patch` files.

# Tests
  - [x] Please check the API updates for any breaking changes that affect our code.
  - [x] Please check for new proposal types.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@dskloetd please review

**Comment by dskloetd** [comment]
Can you make a PR from your own account so it doesn't look like an automated PR when I browse https://github.com/dfinity/nns-dapp/commits/main ?

Also, the patch files don't look like they would be crafted manually. Did you mean something else in the PR description?

**Comment by lmuntaner** [comment]
> Can you make a PR from your own account so it doesn't look like an automated PR when I browse https://github.com/dfinity/nns-dapp/commits/main ?
> 
> Also, the patch files don't look like they would be crafted manually. Did you mean something else in the PR description?

No, I can't do it from my machine because I can't run the script.

I don't think the time to do the changes manually pays off for the commit history.

**Comment by dskloetd** [comment]
You don't need to run the script again. The changes have already been made. I didn't need to run the script to create this PR: https://github.com/dfinity/nns-dapp/pull/3531

I don't think I understand. Did you actually manually type `9e782c650..5cebd0ad6` etc. into the patch file? If so, please describe where you got that from because.

**Comment by lmuntaner** [comment]
> You don't need to run the script again. The changes have already been made. I didn't need to run the script to create this PR: #3531

True! I can easily create another branch and that's it. Thanks!
 
> I don't think I understand. Did you actually manually type `9e782c650..5cebd0ad6` etc. into the patch file? If so, please describe where you got that from because.

Yes, I did that.

I'll add more context in the description of hte next PR.

I got it from here: https://github.com/dfinity/nns-dapp/actions/runs/6480889411/job/17597322117?pr=3526#step:5:43

**Comment by lmuntaner** [comment]
Closing in favor of #3533

**Pull request closed without merging**
