### PR TITLE
Enable screenshots

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
Seeing screenshots might be helpful for debugging

# Changes
- Enable screenshots via the existing env var.
- Retain screenshots for a week, so that the storage costs don't soar.

# Tests
See CI

### CODE REVIEW

**Comment by bitdivine** [comment]
Screenshots were not being downloaded because the uploader was looking in `screenshots` instead of `e2e-tests/screenshots`.  There are screenshots now.  See: https://github.com/dfinity/nns-dapp/actions/runs/4056838965

**Review by peterpeterparker — APPROVED** [review]
Nice, thanks a lot.

An idea: we can maybe spare few MB of screenshots by skipping taking these for the II login?

**Comment by bitdivine** [comment]
@peterpeterparker  Yes, I did notice that there are quite a few screenshots for login.  Maybe make screenshotting optional, off by default, and on only for the "home" e2e test that tests registering and logging in.

**Comment by peterpeterparker** [comment]
Maybe yes or "if localhost.includes(nns-dapp canister id) => no screenshot" or something. Anyhow it's already super cool

**Pull request merged**
