### PR TITLE
L2-842: New Spawn Neuron Modal

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Implement the new Spawn Neuron Modal

# Changes

* Use different components for screens while spawning a neuron.
* Add new ConfirmSpawnHW component.

# Tests

* Adapt test to new flow.

### CODE REVIEW

**Comment by lmuntaner** [comment]
New UX approved by Mischa. Does not adapt 100% to the design, but it's ok.

https://user-images.githubusercontent.com/4550653/178547215-c95b2aea-b862-4815-8864-615f424cc11e.mov

https://user-images.githubusercontent.com/4550653/178547225-9a89346f-4e90-43b6-a875-b381777c7948.mov

https://user-images.githubusercontent.com/4550653/178547236-80395414-03fa-49aa-a19d-b4ea1093cf99.mov

**Comment by lmuntaner** [comment]
@peterpeterparker @mstrasinskis please review

**Comment by peterpeterparker** [comment]
Code wise looks good but UI wise the spacing feels a bit odd to me. Is it the final layout and is it what Mischa designed?

Rough mockup of aligments

Capture d’écran 2022-07-13 à 06 56 09

Capture d’écran 2022-07-13 à 06 54 28

**Comment by lmuntaner** [comment]
Correct, these modals are following the current design, not the new design. I checked with him and we agreed.

As we change the buttons and the new modal in other PRs, it will look more like Mischa's.

Then we'll also realign the items. to two columns instead of title and value below.

If I used exactly Mischa's design here and we go to prod, it would be inconsistent with the rest of the flows.

**Comment by peterpeterparker** [comment]
> Correct, these modals are following the current design

In current design elements of the modal are either aligned top - e.g. maturity and stake in your screenshots or here some other screenshots - or centered if there is only an input but not spread in the modal.

So if the goal is to follow current design, I think that this UI does not match.

But if it's what was defined, of course your call. PR accepted.

Capture d’écran 2022-07-13 à 07 52 18
Capture d’écran 2022-07-13 à 07 51 14
Capture d’écran 2022-07-13 à 07 52 12
Capture d’écran 2022-07-13 à 07 51 08

**Review by peterpeterparker — APPROVED** [review]

**Comment by lmuntaner** [comment]
Yes I agree, the current design is a mess and is not consistent.

I meant more the button at the bottom and the modal. The insides we have every possibility.

**Pull request merged**
