### PR TITLE
GIX-1848: Fix Sent transaction icon background color dark

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

The background of the Sent transaction icon is not visible. See screenshot.

# Changes

* Change the background on dark theme of the send icon for transactions.

# Tests

* Only UI changes.

# Todos

- [x] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
Before:

Screenshot 2023-09-11 at 11 14 21

After:

Screenshot 2023-09-11 at 11 14 12

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Review by peterpeterparker — COMMENTED** [review]
LGTM, thanks

(still good in light mode too right?)

**Comment by lmuntaner** [comment]
> LGTM, thanks
> 
> (still good in light mode too right?)

Yes, correct.

Btw, you didn't approve 😂

**Review by peterpeterparker — APPROVED** [review]
My bad 🤦‍♂️.

Now approved, thanks.

**Pull request merged**
