### PR TITLE
build: bump agent-js v0.15.3

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

ECDSA key for auth-client for more security.

# Notes

- Because of this upgrade, all users that are signed-in next time a release is published might have to sign-up again. Not sure agent-js migrate the key.

- We skip agent-js v0.15.2 because there was a CORS issue .

# Changes

- bump ic-js and agent-js `v0.15.3`

### CODE REVIEW

**Review by lmuntaner — COMMENTED** [review]
Thanks, sorry, I didn't know this was a priority.

Not approving yet until the tests are fixed and you have a reply from the SDK team

**Comment by krpeacock** [comment]
I'll see if I can help with the tests now. 

Behind the scenes, the auth-client will continue to use an existing ED2519 key if one was already stored. You may want to wipe existing keys manually if you want to guarantee that your users switch to ECDSA

**Comment by peterpeterparker** [comment]
thanks for the help @krpeacock, looks good.

@lmuntaner PR is ready for review, go for it

**Review by lmuntaner — APPROVED** [review]
Thanks @krpeacock  and @peterpeterparker !

**Pull request merged**
