### PR TITLE
Rebake fonts with set width for numbers

### PR DESCRIPTION
**Pull request by coskucinkilic**
# Motivation

Have numbers aligned in tables

# Changes

Rebake the fonts with set width for numbers [0-9]

# Tests
I am not sure what happened in CI but please check screenshots updates, i believe it doesn't represent the reality, maybe we need to trigger a clean build to load the fonts properly, i am not sure. but please compare local results vs e2e test outcomes. ( need help with this )

Need to be tested manually as there is no code change, and it affects everything as the underlying font has been forged.
Screenshot from local:
Screenshot 2024-09-24 at 17 01 50
with old fonts:
Screenshot 2024-09-24 at 17 15 59

# Todos

- [ ] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by coskucinkilic** [comment]
@peterpeterparker this is just a test but thanks for the feedback, i can look into removing all the characters and shrink the size.

**Comment by peterpeterparker** [comment]
> this is just a test

You might want to turn the PR into a draft

> i can look into removing all the characters and shrink the size

👍

**Comment by coskucinkilic** [comment]
@peterpeterparker Size has been reduced for both fonts now it is smaller than the old one. I have also centered the numbers in width

**Comment by peterpeterparker** [comment]
Nice! 

Not familiar with the process and out of curiosity, may I ask, did you use a particular tool to shrink the fonts?

**Comment by coskucinkilic** [comment]
@peterpeterparker I used font forge made some changes, exported .otf and converted it on https://transfonter.org/ to woff2. that gave me the best outcome. Apparently Artem and Andrew discussed this and they decided that this is not needed so i am closing this PR. It was fun to play with fonts.

**Comment by peterpeterparker** [comment]
It's good to know and thanks for the tips!

**Pull request closed without merging**
