### PR TITLE
Style test banner

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

Make test banner sticky and review design colors.

# Screenshot

Capture d’écran 2023-05-24 à 11 22 45
Capture d’écran 2023-05-24 à 11 23 20

### CODE REVIEW

**Review by lmuntaner — APPROVED** [review]
Now will be on top of the page, right? LGTM!

**Comment by peterpeterparker** [comment]
> Now will be on top of the page, right?

@lmuntaner not sure what you mean?

The test banner was already at the top but, it added an offset for the content.
With the PR, there is no more offset and the banner appears over (z-index).
The offset always felt a bit weird, was my idea but, felt weird to me too.

**Comment by lmuntaner** [comment]
> > Now will be on top of the page, right?
> 
> @lmuntaner not sure what you mean?
> 
> The test banner was already at the top but, it added an offset for the content. With the PR, there is no more offset and the banner appears over (z-index). The offset always felt a bit weird, was my idea but, felt weird to me too.

I meant exactly what you said. It appears over with the z-index, hehe. Sorry for the miscommunication.

**Comment by peterpeterparker** [comment]
Ah cool then, all good! Thanks for the review

**Pull request merged**
