### PR TITLE
Feat: Add ckETH logos

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Logos for ckETH need to be hardcoded for now.

Here I add them to assets to be reused in upcoming PRs.

# Changes

* Two new assets for ckETH logos

# Tests

Not necessary.

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3865** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/3865?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/3865?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Review by peterpeterparker — COMMENTED** [review]
For consitency reason, what about following names?

ckETH.svg
ckSepoliaETH.svg

**Comment by lmuntaner** [comment]
> For consitency reason, what about following names?
> 
> ckETH.svg ckSepoliaETH.svg

ckETH.svg makes sense, but the other one is not only Sepolia, I guess it could be used for any ETH test token.

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Comment by peterpeterparker** [comment]
> ... I guess it could be used for any ETH test token.

Sepolia is the main ETH testnet, I doubt we will use anything else.

**Comment by peterpeterparker** [comment]
the `ckTESTETH.svg` to reflects `ckTESTBTC.svg` ?

**Comment by lmuntaner** [comment]
> > ... I guess it could be used for any ETH test token.
> 
> Sepolia is the main ETH testnet, I doubt we will use anything else.

There are plans for more ckERC-20 tokens. Doesn't it make sense to have the same token?

Actually, this is temporary in NNS Dapp. I'll rename. While it's temporary it's only Sepolia, true.

**Comment by lmuntaner** [comment]
@peterpeterparker ready for review

**Comment by peterpeterparker** [comment]
> There are plans for more ckERC-20 tokens.

Same testnet, Sepolia.

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Comment by lmuntaner** [comment]
> > There are plans for more ckERC-20 tokens.
> 
> Same testnet, Sepolia.

Ah! Sepolia is the name of the testnet. I didn't know that, thanks!

**Pull request merged**
