### PR TITLE
Fix: Tooltip Split Sns Neuron Button

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Tooltip is misplaced for the Split SNS neuron button.

# Changes

* Add style to wrapper of the button to set the tooltip.

# Tests

Only style issues.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Review by peterpeterparker — COMMENTED** [review]
LGTM

**Comment by lmuntaner** [comment]
@peterpeterparker you didn't approve it, 😂

**Review by peterpeterparker — APPROVED** [review]
Typical me 😅

**Pull request merged**
