### PR TITLE
Chore: Remove unused add_pending_transaction functionality

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Remove unused functionality.

The method `add_pending_notify_swap` was created for SNS-1 before the ticketing system was in place. It helped with the edge case of a user making the transaction and then not notifying the swap canister about it.

This flow is not necessary anymore with the ticket system.

In this PR, I removed the method `add_pending_notify_swap` and everything related to it.

# Changes

* Remove `addPendingNotifySwap` from NnsDappCanister class.
* Remove the method and types from NNS Dapp candid and related files.
* Remove unused `NotAuthorizedError` which was used only in `addPendingNotifySwap`.
* Remove method `add_pending_transaction` and related methods from backend AccountsStore.
* Remove canister module swap that was used only to handle swap transactions.
* Remove candid method `add_pending_notify_swap` from `main.rs` and related method.
* Remove handling the ParticipateSwap transaction in the periodic task runner.
* Remove unused time_millis.

# Tests

I deployed the canister locally and tested all the different transactions. All worked as expected.

* Remove tests for `addPendingNotifySwap`.
* Remove method from nns-dapp-exports tests.
* Remove backend tests related to the functionality.

# Todos

- [x] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #4500** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/4500?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/4500?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
Tested locally with all the transactions:

**Comment by lmuntaner** [comment]
@mstrasinskis please review

**Comment by lmuntaner** [comment]
@dskloetd please review

**Comment by mstrasinskis** [comment]
Do you know, is `refresh_buyer_tokens` still in use?

**Comment by mstrasinskis** [comment]
> Tested locally with all the transactions:
> 
> 

The screenshot looks broken.

**Comment by lmuntaner** [comment]
> The screenshot looks broken.

Broken how?

**Comment by lmuntaner** [comment]
> Do you know, is `refresh_buyer_tokens` still in use?

Yes, that's used from the client though, not fro the canister anymore.

**Comment by mstrasinskis** [comment]
> Broken how?

It's not visible: 
image

But not a blocker.

**Pull request merged**
