### PR TITLE
GIX-1938: Upgrade gix-components. New Tag.

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Use new Tag UI.

In this PR, upgrade gix-components.

# Changes

Only automatic changes from running `npm run update:gix`.

# Tests

Still passing.

# Todos

- [x] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
New UI:

Screenshot 2023-10-09 at 13 18 29
Screenshot 2023-10-09 at 13 18 36
Screenshot 2023-10-09 at 13 19 26
Screenshot 2023-10-09 at 13 20 32

**Comment by lmuntaner** [comment]
Deployed here: https://e3ozm-oyaaa-aaaaa-aaemq-cai.nnsdapp.dfinity.network

**Comment by lmuntaner** [comment]
@peterpeterparker @dskloetd please review

Code is ready, Artem wants to do a final check, but I don't expect any changes.

**Comment by lmuntaner** [comment]
Approved by Artem

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
