### PR TITLE
Chore: Migreate rename canister modal

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Migrate tests to vitest.

In this PR, migrate RenameCanisterModal.

# Changes

* Move RenameCanisterModal to vitest.
* Remove `blockAllCallsTo`. That it was passing before it was an error. This should be used with a fake at the same time. This test has no fakes; therefore, the call to `blockAllCallsTo` is not necessary.

# Tests

* Only test changes.

# Todos

- [ ] Add entry to changelog (if necessary).
Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Comment by lmuntaner** [comment]
@peterpeterparker ready for another review

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks

**Comment by peterpeterparker** [comment]
This PR probably needs #3502 to go through.

**Pull request merged**
