### PR TITLE
GIX-1268: Update CF text

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Update text for the Community Fund card.

# Changes

* Changes in i18n.
* Changes in line height of additional info in NeuronJoinFundCard.svelte

# Tests

Not applicable

### CODE REVIEW

**Comment by lmuntaner** [comment]
New UI:

Screenshot 2023-01-30 at 11 34 47

No line-height changes:

Screenshot 2023-01-30 at 11 34 57

@peterpeterparker @mstrasinskis should we add this in KeyValuePairInfo component?

**Comment by lmuntaner** [comment]
@mstrasinskis @peterpeterparker please review

**Comment by peterpeterparker** [comment]
@lmuntaner should we review even it it's a draft or should we wait?

**Comment by lmuntaner** [comment]
> @lmuntaner should we review even it it's a draft or should we wait?

You can review, if it changes, only the text will change.

**Review by mstrasinskis — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
