### PR TITLE
Update SNS Aggregator Response

### PR DESCRIPTION
**Pull request by sa-github-api**
# Motivation
We would like to keep the ProdLaunchpad.spec up to date with mainnet data.

# Changes
* Update the files used for the fetch mock in ProdLaunchpad.spec.

# Tests
Only test changes.

### CODE REVIEW

**Comment by dskloetd** [comment]
@lmuntaner should we be concerned that the third page is already the largest?

**Comment by bitdivine** [comment]
I'll keep this one open to keep your conversation.

**Comment by lmuntaner** [comment]
> @lmuntaner should we be concerned that the third page is already the largest?

It's not. [Page 1](https://github.com/dfinity/nns-dapp/blob/bb56f24230a9a97c52a7c618fc8d21cb2cf26c02/frontend/src/tests/workflows/Launchpad/sns-agg-page-1.json) is 6k lines and [Page 2](https://github.com/dfinity/nns-dapp/blob/bb56f24230a9a97c52a7c618fc8d21cb2cf26c02/frontend/src/tests/workflows/Launchpad/sns-agg-page-2.json) is 4k lines

**Comment by dskloetd** [comment]
OK, I must have misunderstood the GitHub UI. Still surprising given that the second page contains 10 projects and the third page just 1 if I'm not mistaken.

**Comment by lmuntaner** [comment]
> OK, I must have misunderstood the GitHub UI. Still surprising given that the second page contains 10 projects and the third page just 1 if I'm not mistaken.

The third page has three projects...

**Comment by dskloetd** [comment]
OK, thanks. This PR adds the third page for the first time right? Anyway, lets' merge it.

**Review by dskloetd — APPROVED** [review]

**Pull request merged**
