### PR TITLE
test: migrate metrics, project-details, same, summary and transaction components to vitest

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Changes

- migrate more components to vitest
- in `sns.mock` replace `jest.fn` with a `() => {}`
- modify `TotalValueLocked.spec.ts` to check for class `visible` to be falsy instead of using `toBeVisible` which behaves more accuratly or differently with vitest dom + last testing library

# Excluded

- Can you have a look to the migraiton of `Summary.spec.ts` @lmuntaner ? Something related to the function `mockProjectSubscribe` seems to not be compatible.

### CODE REVIEW

**Review by lmuntaner — APPROVED** [review]

**Comment by lmuntaner** [comment]
@peterpeterparker I added moving Summary.spec to vitest to my todos.

**Comment by peterpeterparker** [comment]
Thx!

**Comment by peterpeterparker** [comment]
@lmuntaner I had a similar problem as `mockProjectSubscribe` in another PR and I could resolve it by simply make `run` optional. Good chance it's the same solution here.

Is:

```
export const mockProjectSubscribe =
  (projects: SnsFullProject[]) =>
  (run: Subscriber<SnsFullProject[]>): (() => void) => {
    run(projects);

    return () => undefined;
  };
```

To:

```
export const mockProjectSubscribe =
  (projects: SnsFullProject[]) =>
  (run: Subscriber<SnsFullProject[]> | undefined): (() => void) => {
    run?.(projects);

    return () => undefined;
  };
```

**Comment by lmuntaner** [comment]
> @lmuntaner I had a similar problem as `mockProjectSubscribe` in another PR and I could resolve it by simply make `run` optional. Good chance it's the same solution here.
> 
> Is:
> 
> ```
> export const mockProjectSubscribe =
>   (projects: SnsFullProject[]) =>
>   (run: Subscriber<SnsFullProject[]>): (() => void) => {
>     run(projects);
> 
>     return () => undefined;
>   };
> ```
> 
> To:
> 
> ```
> export const mockProjectSubscribe =
>   (projects: SnsFullProject[]) =>
>   (run: Subscriber<SnsFullProject[]> | undefined): (() => void) => {
>     run?.(projects);
> 
>     return () => undefined;
>   };
> ```

Ok, thanks!

**Pull request merged**
