### PR TITLE
Feat: Add typed json mock import

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Avoid casting a json import for mock data of the aggregator.

Source: https://github.com/microsoft/TypeScript/issues/48364#issuecomment-1384518686

I discovered it here: https://twitter.com/mattpocockuk/status/1696450304131092791

# Changes

* Add type file for the aggregator.json
* Add types inside.

# Tests

Only test changes.

# Todos

- [ ] Add entry to changelog (if necessary).
Not necessary.

### CODE REVIEW

**Comment by dskloetd** [comment]
The [comment you linked](https://github.com/microsoft/TypeScript/issues/48364#issuecomment-1384518686) suggests keeping the JSON data in the `.json` file and putting the type of JSON in the `.d.json.ts` file.

If it looks like you put the entire data in the `.d.json.ts` file. Am I missing something?

Also, the comment is about not slowing down intellisense. Did you perhaps, mean to link a different comment?

**Comment by lmuntaner** [comment]
> The [comment you linked](https://github.com/microsoft/TypeScript/issues/48364#issuecomment-1384518686) suggests keeping the JSON data in the `.json` file and putting the type of JSON in the `.d.json.ts` file.
> 
> But it looks like you put the entire data in the `.d.json.ts` file. Am I missing something?
> 
> Also, the comment is about not slowing down intellisense. Did you perhaps, mean to link a different comment?

Thanks!

I set it as draft and removed you from review while I was playing with it. Sorry to have triggered it before it was ready.

**Comment by lmuntaner** [comment]
@dskloetd ready for review

**Comment by dskloetd** [comment]
Can you fix the PR description?

**Review by dskloetd — APPROVED** [review]

**Pull request merged**
