### PR TITLE
L2-411: SkeletonCard when loading cards

### PR DESCRIPTION
**Pull request by lmuntanerDfinity**
# Motivation

User has a nice experience when waiting for lists.

# Changes

* New spinner "SkeletonCard".
* Use spinner in routes as well as in SelectAccounts screen.

# Tests

* Add data-tid="spinner" to SkeletonCard to keep tests.

### CODE REVIEW

**Comment by lmuntanerDfinity** [comment]
Some pages:

Screenshot 2022-04-28 at 15 27 55

Screenshot 2022-04-28 at 15 29 21

Screenshot 2022-04-28 at 15 38 10

Screenshot 2022-04-28 at 15 31 10

Screenshot 2022-04-28 at 15 52 11

**Comment by lmuntanerDfinity** [comment]
@mstrasinskis @peterpeterparker please review

**Comment by lmuntanerDfinity** [comment]
Sounds good, I guess we can add it to the `Spinner` and `ParagraphSkeleton`

**Comment by peterpeterparker** [comment]
Oh yes good idea 👍

Note I suggested the role presentation but don't know if there is a role for "loading" purpose?

**Comment by peterpeterparker** [comment]
@lmuntanerDfinity just gave it a try and noticed the layout moving in accounts (lightly) and proprosals (more) tabs.

Can you please improve this please?

ezgif com-gif-maker (1)
ezgif com-gif-maker (2)

**Comment by lmuntanerDfinity** [comment]
Sure, I created the issue, I will do it next.

**Pull request merged**
