### PR TITLE
Chore: Upgrade gix components

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

We added an extra `div` wrapper to PageBanner because there was an issue with grid container inside a flex.

This wrapper was added in the `PageBanner` inside gix-components to avoid putting it in the parent.

In this PR, we upgrade gix-components.

Next PR, remove the wrapper in NNS dapp.

# Changes

* Upgrade gix-components

# Tests

Not necessary

# Todos

- [ ] Add entry to changelog (if necessary).
Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Review by peterpeterparker — APPROVED** [review]
Thanks

**Comment by lmuntaner** [comment]
@peterpeterparker screenshot testing failed because screenshots changed, but they didn't really change, just some pixels I guess.

You can take a look at the new screenshots to validate it.

**Comment by dskloetd** [comment]
> @dskloetd is there a way to collect the comparison image of playwright? The image that compare the two screenshots and highlights in red where the pixel differences are noticed. Out of curiosity.

I don't see anything like that here: https://playwright.dev/docs/api/class-page#page-screenshot
But to be honest, I would rather expect such functionality in GitHub (I don't see it there either) or which ever other diff tool used to review the change. GitHub reviews are once again disappointing...

**Comment by peterpeterparker** [comment]
@dskloetd oh that's a default feature of playwright, nothing to configure. the question was more if it's possible to access that particular file.

**Comment by dskloetd** [comment]
Then I don't know what you're referring to.

**Comment by peterpeterparker** [comment]
@dskloetd getting the "diff" screenshot

For example:

External-link-is-displayed-with-an-icon-1-diff

Example of output:

- 1 screenshot expected
- 1 screenshot effectivelly tested
- 1 diff with red highlighting

Capture d’écran 2023-08-25 à 10 18 27

**Comment by dskloetd** [comment]
It's it's something that Playwright generates, you could change the workflow to upload it here: https://github.com/dfinity/nns-dapp/blob/main/.github/actions/test-e2e/action.yml#L78
Either temporarily or permanently if it's something we'll need often.

**Comment by peterpeterparker** [comment]
Thanks for the hint! I might have a look and if I do, oviously will let you know.

**Pull request merged**
