### PR TITLE
Fix: Sns Voting Power in PageHeading

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

The voting power was incorrect in the new SNS neuron page heading.

# Changes

* Use util to formatVotingPower in the SnsPageHeading

# Tests

* Add a test to check the value of the voting power in the SnsPageHeading.

# Todos

Not worth an entry yet.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Before:

Screenshot 2023-07-19 at 13 27 08

Now:

Screenshot 2023-07-19 at 13 25 35

**Comment by lmuntaner** [comment]
@mstrasinskis @peterpeterparker please review

**Comment by peterpeterparker** [comment]
Regarding design, if I may ask, shouldn't the voting power be displayed as a value (in your screenshot 22.30 as light as 19.20)?

**Comment by lmuntaner** [comment]
> Regarding design, if I may ask, shouldn't the voting power be displayed as a value (in your screenshot 22.30 as light / white as 19.20)? or it's excepted to be a description?

It's all the same color in the design. I interpret all as a text, not a key-value pair.

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
