### PR TITLE
GIX-1874: Dev example SNS Aggregator landing page

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Make it more obvious how developers can integrate with SNS Aggregator.

# Changes

* Add an example of how to fetch the SNS Aggregator data in the landing page.

# Tests

Not necessary.

# Todos

- [ ] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
New UI:

Screenshot 2023-09-11 at 08 52 40

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Comment by peterpeterparker** [comment]
> I know it's obvious the example, but I don't think we need to get fancy either.

Still, it's a bit a pity to have a section that does not follow the opinionated design and feels a bit off visually speaking. 

Not a must but it would be also neat to add syntax highlighting.

Should I try to style it in another PR or do you want to give it a try?

**Comment by lmuntaner** [comment]
> > I know it's obvious the example, but I don't think we need to get fancy either.
> 
> Still, it's a bit a pity to have a section that does not follow the opinionated design and feels a bit off visually speaking.
> 
> Not a must but it would be also neat to add syntax highlighting.
> 
> Should I try to style it in another PR or do you want to give it a try?

What isn't it following the design? I tried to follow it.

I don't have any syntax highlighting code, I guess you might have it in some of your projects? Let's do that in another PR.

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks.

I can have a look to the design and syntax highlighting when I've got 5min.

**Comment by lmuntaner** [comment]
> LGTM, thanks.
> 
> I can have a look to the design and syntax highlighting when I've got 5min.

Thanks!

**Pull request merged**
