### PR TITLE
feat: import icons from gix-components

### PR DESCRIPTION
**Pull request by wackyleo459**
# Changes
- Imported remaining icons from @dfinity/gix-components library
- Deleted icons folder due to gix-components library as dependency

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@wackyleo459 looks cool!

there is just one typo in an icon so we need to fix that first.

can you review PR 👉 https://github.com/dfinity/gix-components/pull/61

then we can release and update gix-components and we good to go 😃

**Comment by wackyleo459** [comment]
@peterpeterparker I went ahead to approve and merge that PR 61. Good catch!

**Comment by peterpeterparker** [comment]
@wackyleo459 super, thanks!

I just released a new version of gix-components to npm so can you `npm run update:gix` in this PR please?

**Comment by peterpeterparker** [comment]
@mstrasinskis has bumped gix-components in PR  #1315 so no need to update here, I just gonna update `main` and it will do the tricks

**Review by peterpeterparker — APPROVED** [review]
Good things done, thanks a lot!

Gonna merge it for you right now.

**Pull request merged**
