### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by mstrasinskis**
# Motivation

Release candidate 2022-11-16

# Changes

Update changelog

### CODE REVIEW

**Comment by lmuntaner** [comment]
@mstrasinskis will you update the versions and add the proposal number or shall I do that?

**Comment by peterpeterparker** [comment]
@lmuntaner @mstrasinskis this should be closed or merged?

**Comment by lmuntaner** [comment]
> @lmuntaner @mstrasinskis this should be closed or merged?

Merged, but still needs some additional change. That's why I added the comment.

**Comment by lmuntaner** [comment]
Done in #1572

**Pull request closed without merging**
