### PR TITLE
NNS1-2851: Remove loadSnsAccountTransactions

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Unify wallet implementation.

In this PR, remove `loadSnsAccountTransactions` service.

# Changes

* Remove flag `loadTransactions` in SnsTransactionModal that was used only in wallet page.
* Remove flag `loadTransactions` in `snsTransferTokens`.
* Remove file sns-transactions services.

# Tests

* Remove test `"should load transactions if flag is passed"` for `snsTransferTokens`.
* Remove spec file sns-transactions services.

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #4467** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/4467?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/4467?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
@dskloetd please review

**Comment by dskloetd** [comment]
Can you explain (in the PR description) why this can be removed?

**Comment by dskloetd** [comment]
Ah, sorry, I found it now: "was used only in wallet page."

**Review by dskloetd — APPROVED** [review]
Thanks!

**Pull request merged**
