### PR TITLE
Chore: Revert upgrade dfx

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

There are problems to connect to the dev environments using dfx 0.15.

In this PR, revert back to 0.14

# Changes

* Change dfx and snsdemo versions.

# Tests

Still passing.

# Todos

- [x] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3798** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/3798?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/3798?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
@dskloetd @bitdivine please review

**Comment by dskloetd** [comment]
?

**Comment by lmuntaner** [comment]
This is already done. I didn't pull latest changes from `main`.

**Pull request closed without merging**
