### PR TITLE
GIX-2188: Remove unused components

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Clean up code after removing `ENABLE_MY_TOKENS`.

# Changes

* Remove all non-NNS cmponets within Accounts.

# Tests

* Remove the tests of the removed components.

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #4431** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/4431?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/4431?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
@dskloetd please review

**Comment by dskloetd** [comment]
Can you add a PR description?

**Comment by lmuntaner** [comment]
> Can you add a PR description?

Oops, sorry. Done!

**Pull request merged**
