### PR TITLE
build: Add Eslint

### PR DESCRIPTION
**Pull request by lmuntanerDfinity**
# Motivation

Add Eslint setup. No rules enforced until team decision.

# Changes

* Install Eslint dependencies.
* Setup `eslintrc.js`

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@mstrasinskis works for you too?

**Review by mstrasinskis — COMMENTED** [review]
Is there already a plan regarding eslint rules?

**Review by mstrasinskis — APPROVED** [review]
LGTM

**Comment by lmuntanerDfinity** [comment]
> Is there already a plan regarding eslint rules?

No plan yet, I will mention it on Monday and we can set a meeting or a document to agree on what rules.

I expect we shuold then add the rules during a quite weekend, otherwise there might be a lot of merge conflicts.

**Pull request merged**
