### PR TITLE
GIX-2080: Remove images e2e test

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Enable tokens page flag for e2e tests.

In this PR, remove the images.spec because it doesn't add much value.

# Changes

* Remove test "images.spec.ts"

# Tests

Only test changes.

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #4242** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/4242?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/4242?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
@dskloetd ready for review

**Comment by dskloetd** [comment]
I'm not sure about the value of this test. I created it because there was something similar with the old e2e tests.
I don't think we need 2 of them. What do you think?

**Comment by lmuntaner** [comment]
> I'm not sure about the value of this test. I created it because there was something similar with the old e2e tests. I don't think we need 2 of them. What do you think?

I'm also not sure. The screenshot testing cover the same thing.

Shall I remove the images.spec as is then?

**Comment by dskloetd** [comment]
> Shall I remove the images.spec as is then?

ok

**Comment by lmuntaner** [comment]
@dskloetd please review

**Review by dskloetd — APPROVED** [review]

**Pull request merged**
