### PR TITLE
Fix Hash reload issue

### PR DESCRIPTION
**Pull request by coskucinkilic**
# Motivation

There is an existing issue related to stopPropagation onClick events, it was stopping internal Svelte routing system to catch the routing event and resolve DOM diff correctly, that is why it was causing a full reload.

We don't want this to happen in any component who uses Hash that also need navigation on onclick events. 

You can see similar structure in NeuronsTable which has this reload issue, if you click on the Hash not the row, the page is reloading right now.

# Changes

PreventDefault is added so onclick on Hash wouldn't trigger routing when used in a parent which changes the route on click.

# Tests

manually tested

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary

### CODE REVIEW

**Comment by dskloetd** [comment]
Can you give more details in the PR description?
What is the exact issue that happens specifically and why does this solve it?

**Comment by dskloetd** [comment]
> We don't want this to happen in any component who uses Hash that also need navigation on onclick events.

Does such a component exist? Did you actually run into this? Or is this purely hypothetical?

**Comment by coskucinkilic** [comment]
@dskloetd i have updated the description to include the information you are looking for

**Comment by dskloetd** [comment]
Thanks for pointing to the neurons table. Good catch!

But I don't understand how adding `preventDefault` fixes this.
My understanding is that Svelte has some top-level click listener, which if you click on a link that points inside the app, will prevent the default navigation behavior and route your app to the intended view for that URL. By adding `stopPropagation`, you prevent this Svelte listener from doing its job, which results in doing the external navigation instead of the internal navigation. But if you just add `preventDefault`, I would expect that to result in no navigation at all.

If you click on the `Hash` component now, does it use Svelte's internal navigation again? Or does it not navigate at all?

I would expect the proper solution to be that if `isClickable` is false, the event propagation shouldn't be stopped at all.

**Review by dskloetd — APPROVED** [review]

**Comment by coskucinkilic** [comment]
First I didn't add stopPropagation, it was there before, i just added preventDefault to make sure that clicks inside the Hash wouldn't trigger navigation and indeed prevents the navigation on click on Hash in Neurons table.

I don't know the reason why we have stopPropagation on click. I thought that must have a use, so I did the second best option to fix the reload issue.

I have checked why there is a default stopPropagation on onclick event and there is no usecase, so i created a solution that follows your idea, stopPropagation is only applied if the Hash is clickable, and for all other Hash usage it should propagate. 

This allows NeuronRow to navigate without reload, and also click events are not propagated if Hash is clickable.

**Pull request merged**
