### PR TITLE
build: review chunking strategy to improve performance and avoid FOUC

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

Replicate the chunking strategy implemented in the [Oisy Wallet](https://github.com/dfinity/oisy-wallet) for the following purposes:

1. Enhance boot time performance by reducing the number of chunks. It appears that loading fewer chunks, especially considering network latency, results in a perceived improvement in loading speed.
2. Address random FOUC issues.

# PRs

- [x] This PR requires #3394 to build

# Changes

- update `manualChunks` Rollup's strategy in vite config

# Observations

Build and served locally. Observed on main page while not being sign-in.

Current `main` branch :

JS:
- 37 requests
- 625kb

CSS:
- 23 requests
- 30.1 kb

CSS+JS:
- 60 requests (83% of all requests)
- 655.1kb (79% of everything downloaded)

`PR`:

JS:
- 7 requests (-71%)
- 772kb (+15%)

CSS:
- 1 request
- 21.5kb (-28%)

CSS+JS:
- 8 requests (50% of all requests)
- 793.5 (82% of everything downloaded)

* the comparison to "all requests and everything downloaded" might not be fully accurate as other queries such as fetching data might be counted. it's more an informal info.

# Screenshots

`main`

Capture d’écran 2023-09-27 à 12 56 23
Capture d’écran 2023-09-27 à 12 56 27

`PR`

Capture d’écran 2023-09-27 à 13 16 40
Capture d’écran 2023-09-27 à 13 16 38

### CODE REVIEW

**Comment by peterpeterparker** [comment]
As this PR aims to review the chunking strategy, @dskloetd do you want to perform additional checks on reproducibility than what's done in the CI?

**Review by bitdivine — APPROVED** [review]
LGTM, thanks!

**Comment by dskloetd** [comment]
> As this PR aims to review the chunking strategy, @dskloetd do you want to perform additional checks on reproducibility than what's done in the CI?

Maybe you can try your script that builds 100 times?

**Comment by peterpeterparker** [comment]
Good idea!

**Pull request merged**
