### PR TITLE
Feat: Minor change disbursing maturity UI

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Final UI improvements for Disbursing maturity flow.

# Changes

* Rename buttons to "Stake" and "Disburse".
* Change font-size of description in confirmation screen.

# Tests

Only UI changes.

# Todos

- [ ] Add entry to changelog (if necessary).
Covered by disbursing maturity entry.

### CODE REVIEW

**Comment by lmuntaner** [comment]
New UI:

Screenshot 2023-09-19 at 08 47 53
Screenshot 2023-09-19 at 08 58 26

**Review by dskloetd — APPROVED** [review]

**Comment by dskloetd** [comment]
In the screenshot where it says "Maturity disbursed", that maturity is not yet disbursed, right?
Shouldn't it says "Maturity disbursing" instead?

**Comment by dskloetd** [comment]
Ah, CI finally broke as well.

**Comment by lmuntaner** [comment]
> In the screenshot where it says "Maturity disbursed", that maturity is not yet disbursed, right? Shouldn't it says "Maturity disbursing" instead?

Good point, I'll change it.

**Pull request merged**
