### PR TITLE
No flutter

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
We wish to get rid of flutter from our codebase.  It is no longer used, the size of the flutter blocks other PRs that need more space (in particular our backend formatting function for proposals which needs another 0.6MiB, mostly eating up our savings from removing flutter).

# Changes
- Delete `/frontend/dart` and `/frontend/ts`
- Move files that are still needed to other places:
  - Move `config.json` (the file compiled from dfx.json for a specific deployment) from `/frontend/ts/...` to the root of the repo.
  - Move static assets from under `/frontend/dart/assets` to `/frontend/svelte/assets`
    - Note: I also removed the double `assets` in URLs; technically this is not needed in this PR and I can revert this if wanted.  Given that the manifest pulls assets from the hard-wired URL `https://nns.raw.ic0.app/assets/assets/...`, removing the repetition means that favicons do not render on the testnet.
- Add a redirect from `/v2/` to `/`.
- Remove CI tests, gitignore and dockerignore and documentation for dart, flutter and `frontend/ts`.

# Tests
- Deployed to https://y3cxn-3yaaa-aaaaa-aabra-cai.nnsdapp.dfinity.network
- Verified that redirects work and preserve the hash, so e.g deep links still work.  E.g. try clicking here, even if logged out: 
  - / version: https://y3cxn-3yaaa-aaaaa-aabra-cai.nnsdapp.dfinity.network/#/proposal/196
  - /v2 version: https://y3cxn-3yaaa-aaaaa-aabra-cai.nnsdapp.dfinity.network/v2/#/proposal/196
- Verified that there are no console errors, apart from those expected due to stopping the asset repetition.

### CODE REVIEW

**Comment by lmuntaner** [comment]
This is beautiful.

I played with the testnet and everything looked good. Except a 404 for https://nns.raw.ic0.app/assets/favicons/icon-192x192.png  and that I can't get icps there and therefore couldn't test the functionality.

**Comment by bitdivine** [comment]
@peterpeterparker - sure thing, I can rename that.

Regarding /v2/ - try the links in the testing section of the description. :-)

**Comment by bitdivine** [comment]
@lmuntaner Thank you for your review.  Sorry this is a bit more of a monster than I was hoping for. Still, it is mostly deletion or renaming.  I have topped up the moneybags with 1000ICP by sending back money from another account, so if you log in as user 10000 you will have 11 ICP, for example, or using "get ICP" should work again.

@peterpeterparker I have renamed `public_template` to `static` as requested.

**Comment by peterpeterparker** [comment]
Thanks for the renaming and redirection @bitdivine, super 👍

**Comment by lmuntaner** [comment]
@bitdivine all good now! Tested different pages refreshing there and testing redirects.

We need to tell the dashboard to change the links without `/v2` as soon as we release.

**Review by lmuntaner — APPROVED** [review]
Amazing, thanks!

**Pull request merged**
