### PR TITLE
[DO NOT MERGE] Svelte

### PR DESCRIPTION
**Pull request by bitdivine**
# Release branch

This branch will be used for the next svelte-based releases, so it will be merged into main and released several times.

### CODE REVIEW

**Comment by saikatdas0790** [comment]
@bitdivine Very excited for this. I'm a Svelte dev. Are there open issues I can take a look at?

**Comment by bitdivine** [comment]
@saikatdas0790 Hello!  Good to see you so excited! :-)  I have played with both the rollup and the vite version, both seemed fine from a productivity standpoint.  As security is very important in this context the more secure option is likely to be the winner.  It is a dev tool, but dev tools can slip nasties into production builds.  I was going to hand svelte and rollup as options to a security team.  Do you know of any existing in depth security reviews of these tools?

**Comment by saikatdas0790** [comment]
@bitdivine I know of this
https://bundlers.tooling.report/

But I don't know of publicly available security reviews. Maybe someone on the Svelte Discord does.

**Comment by bitdivine** [comment]
Svelte has been added in other PRs.

**Pull request closed without merging**
