### PR TITLE
Chore: Change i18n value

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Inconsistency in how the topic is displayed in the proposals and in the list of topics for followees.

# Changes

* Change the value of `topic_8_title`.

# Tests

Text not tested directly.

# Todos

- [x] Add entry to changelog (if necessary).

### CODE REVIEW

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Comment by lmuntaner** [comment]
@peterpeterparker in another PR we shuold try to use the same i18n keys in proposals and topics, wdyt?

**Review by peterpeterparker — APPROVED** [review]
LGTM

**Comment by peterpeterparker** [comment]
> in another PR we shuold try to use the same i18n keys in proposals and topics, wdyt?

If they do not differ, why not 👍

**Pull request merged**
