### PR TITLE
feat: add period at the end of description

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

According @dylancm4 there should be a period at the end of the descriptions in `en.governance.json`.

### CODE REVIEW

**Review by mstrasinskis — APPROVED** [review]
LGTM, thank you!

**Comment by mstrasinskis** [comment]
@peterpeterparker could you please recheck `topics_description.topics_description`?

**Review by mstrasinskis — APPROVED** [review]
LGTM, just a single latecomer comment.

**Comment by peterpeterparker** [comment]
@mstrasinskis good catch, one period was missing in `SubnetManagement` description

**Pull request merged**
