### PR TITLE
Chore: Revert build scripts

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Revert which build scripts are set in dfx.json for NNS Dapp and SNS Aggregator.

docker-build script is not yet working for M1.

# Changes

* Revert dfx.json "build" field for nns-dapp and sns_aggregator

# Tests

Not applicable

### CODE REVIEW

**Comment by lmuntaner** [comment]
@dskloetd @bitdivine please review

**Comment by dskloetd** [comment]
Approving because this is preventing people from deploying.
We better try this again when Max has time to help people debug.

**Review by dskloetd — APPROVED** [review]

**Review by bitdivine — APPROVED** [review]
Thanks!

**Comment by dskloetd** [comment]
I don't have notes. It was in my first week. I don't remember actually getting it to work. I remember solving some issues but I think I get distracted by something else before it was fully working.

**Pull request merged**
