### PR TITLE
Fix: Name of the script in the workflow

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Fix failing CI.

# Changes

* The name of the shell file was wrong.

# Tests

Not necessary.

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #4438** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/4438?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/4438?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
@bitdivine please review

**Review by bitdivine — COMMENTED** [review]
LGTM, thanks!

**Review by bitdivine — APPROVED** [review]

**Comment by lmuntaner** [comment]
> LGTM, thanks!

You didn't approve 😰

**Pull request merged**
