### PR TITLE
Chore: Improve Participate Button

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Improve the location of the Participate button for small devices.

# Changes

* Wrap Participate button with BottomSheet.

# Tests

No tests, only UI changes.

### CODE REVIEW

**Comment by lmuntaner** [comment]
New UI:

Screenshot 2022-11-11 at 10 32 50
Screenshot 2022-11-11 at 10 33 18

**Comment by lmuntaner** [comment]
@mstrasinskis @peterpeterparker please review

**Review by mstrasinskis — APPROVED** [review]
LGTM

**Comment by peterpeterparker** [comment]
@lmuntaner the button should probably not be set as full width

**Comment by lmuntaner** [comment]
> @lmuntaner the button should probably not be set as full width

Let me bring it up with Mischa. I thought that would be the design for bottom buttons to cover the whole width.

**Pull request merged**
