### PR TITLE
L2-276: End-to-end testing with registration

### PR DESCRIPTION
**Pull request by lmuntanerDfinity**
# Motivation

End to end tests registers the devices in II and comes back to NNS dashboard.

# Changes

* New e2e test: "register and back to dashboard".

# Tests

* New e2e test: "register and back to dashboard".

### CODE REVIEW

**Comment by lmuntanerDfinity** [comment]
@mstrasinskis @peterpeterparker please review

There is still work to do with docker and other canisters to implement this in the CI. Which at the moment is above my knowledge. But this is a step forward and we can create a plan on how to bring this to the CI discussing it with @bitdivine and @nmattia

**Comment by peterpeterparker** [comment]
sure will do Monday

**Review by mstrasinskis — APPROVED** [review]
LGTM

**Review by peterpeterparker — CHANGES_REQUESTED** [review]
Cool 👍

Can you just revert the `e2e-tests/package-lock.json` change, it is not related right?

**Comment by lmuntanerDfinity** [comment]
> Cool 👍
> 
> Can you just revert the `e2e-tests/package-lock.json` change, it is not related right?

It was done when I `npm install` it. I am not sure why the change appeared. It might be worth to specify which node and npm version is expected. Maybe in another PR and once Nicolas is back, since he started this project and understands better the dependencies.

**Review by peterpeterparker — APPROVED** [review]
Good idea 👍

Thanks

**Pull request merged**
