### PR TITLE
GIX-2089: Update Send icon

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Icon for the Send action in TokensTable has changed.

# Changes

* Change the icon in the SendButton.

# Tests

Not necessary

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3812** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/3812?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/3812?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
As changed in [Figma](https://www.figma.com/file/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?type=design&node-id=408-3031&mode=design&t=DqiMSTM3MRo6xlCl-0).

New icon:

**Comment by lmuntaner** [comment]
@peterpeterparker please review

**Review by peterpeterparker — APPROVED** [review]
Thanks

**Pull request merged**
