### PR TITLE
Fix: Adapt tokens table border radius

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Tokens table design has a rounded border radius.

# Changes

* Add rounded border radius to TokensTable.

# Tests

Only UI changes.

# Todos

- [ ] Add entry to changelog (if necessary).

Not yet necessary.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3759** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/3759?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/3759?utm_source=stack-comment).

**Comment by lmuntaner** [comment]
New UI:

**Comment by lmuntaner** [comment]
@dskloetd @peterpeterparker please review

**Review by peterpeterparker — APPROVED** [review]
Thx

**Pull request merged**
