### PR TITLE
GIX-1982: Render mobile or desktop tokens component

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Current tokens list is only for desktop devices. The mobile devices will use a different UI.

In this PR, the Tokens page renders either the Desktop or the Mobile component based no window's width.

# Changes

* Add svelte:window to watch window's with in Tokens page and render a different component.
* Setup new component MobileTokensList.

# Tests

* Test that Tokens page renders one or ther other based on window's width.
* Rename TokensPagePO methods.
* Setup MobileTokensListPo.

# Todos

- [ ] Add entry to changelog (if necessary).

Not necessary yet. Part of bigger feature.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3695** <a href="https://app.graphite.dev/github/pr/dfinity/nns-dapp/3695" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/nns-dapp/3695?utm_source=stack-comment).

**Comment by dskloetd** [comment]
The PR you listed as a dependency is this PR itself. Did you mean https://github.com/dfinity/gix-components/pull/329 instead?

**Comment by lmuntaner** [comment]
Where did I list a dependency?

I added a `TODO`, is that what you mean?

**Comment by dskloetd** [comment]
> Where did I list a dependency?

Here: https://github.com/dfinity/nns-dapp/pull/3695#issuecomment-1801298738

image

**Comment by lmuntaner** [comment]
> > Where did I list a dependency?
> 
> Here: [#3695 (comment)](https://github.com/dfinity/nns-dapp/pull/3695#issuecomment-1801298738)
> 
> image

Ah, oh, thanks. That's an automatic comment from the new tool.

**Review by lmuntaner — COMMENTED** [review]
We decided for another approach. Closing.

**Pull request closed without merging**
